/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.fameg.gui;

import br.fameg.domain.Palavra;
import br.fameg.domain.SalvadorDeBancoDePalavras;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Allan
 */
public class CriadorDeBanco extends javax.swing.JFrame {

    /**
     * Creates new form Criar
     */
    public CriadorDeBanco() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        taLista.setEditable(false);
        tfPalavra.requestFocus();
        limparTudo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPainelSul = new javax.swing.JPanel();
        btSalvar = new javax.swing.JButton();
        btAbrir = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        jPanelCentro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfPalavra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfDica = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btAdicionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taLista = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPainelSul.setBackground(new java.awt.Color(204, 204, 204));
        jPainelSul.setToolTipText("");

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPainelSul.add(btSalvar);

        btAbrir.setText("Abrir banco");
        btAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirActionPerformed(evt);
            }
        });
        jPainelSul.add(btAbrir);

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jPainelSul.add(btNovo);

        getContentPane().add(jPainelSul, java.awt.BorderLayout.PAGE_END);

        jPanelCentro.setBackground(new java.awt.Color(153, 153, 153));
        jPanelCentro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 3, true));

        jLabel1.setText("Palavra");

        tfPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPalavraActionPerformed(evt);
            }
        });

        jLabel2.setText("Dica");

        tfDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDicaActionPerformed(evt);
            }
        });

        jLabel3.setText("Palavras Adicionadas");

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        taLista.setColumns(20);
        taLista.setRows(5);
        jScrollPane2.setViewportView(taLista);

        javax.swing.GroupLayout jPanelCentroLayout = new javax.swing.GroupLayout(jPanelCentro);
        jPanelCentro.setLayout(jPanelCentroLayout);
        jPanelCentroLayout.setHorizontalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroLayout.createSequentialGroup()
                .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCentroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfDica, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                    .addComponent(tfPalavra, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanelCentroLayout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(btAdicionar))
                            .addGroup(jPanelCentroLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelCentroLayout.createSequentialGroup()
                .addGroup(jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel2))
                    .addGroup(jPanelCentroLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCentroLayout.setVerticalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfDica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btAdicionar)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDicaActionPerformed

    private void tfPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPalavraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPalavraActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:
        taLista.append(tfPalavra.getText()+"\n");
        Palavra p = new Palavra(tfDica.getText().toUpperCase(), tfPalavra.getText().toUpperCase().trim());
        lista.add(p);
        limparCampos();
        btSalvar.setEnabled(true);
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        String arq = JOptionPane.showInputDialog("Escreva o nome do banco");
        File file = new File(arq+".txt");
        SalvadorDeBancoDePalavras.gravarBanco(lista, file);
        limparTudo();
               
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        limparTudo();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirActionPerformed
        // TODO add your handling code here:
        LeitorDeCruzadinha leitor = new LeitorDeCruzadinha();
        leitor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btAbrirActionPerformed

    private void limparCampos(){
        tfPalavra.setText("");
        tfDica.setText("");
        tfPalavra.requestFocus();
        System.out.println(lista);
        
    }
    private void limparTudo(){
        limparCampos();
        lista.clear();
        taLista.setText("");
        btSalvar.setEnabled(false);
    }
    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriadorDeBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriadorDeBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriadorDeBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriadorDeBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriadorDeBanco().setVisible(true);           
                       
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrir;
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPainelSul;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taLista;
    private javax.swing.JTextField tfDica;
    private javax.swing.JTextField tfPalavra;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Palavra> lista = new ArrayList<>();
}
