/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.fameg.gui;

import br.fameg.domain.GravadorDeImagem;
import br.fameg.domain.LogicaCruzadinha;
import br.fameg.domain.Palavra;
import br.fameg.domain.TransformadorDePalavraEmVetor;
import br.fameg.persistencias.Persistencia;
import br.fameg.resources.PalavraTableModel;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Allan
 */
public class LeitorDeCruzadinha extends javax.swing.JFrame {

    /**
     * Creates new form LeitorDeCruzadinha
     */
    public LeitorDeCruzadinha() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    private void makeCard(String lineToParse) {
        String[] result = lineToParse.split("/");
        Palavra card = new Palavra(result[0], result[1]);
        listaDePalavras.add(card);
        textArea.append((listaDePalavras.size() + ". ") + "" + card.getClue()+" ("+card.getResposta().length()+")" + "\n");

    }
    private void limparCampos() {
        listaDePalavras.clear();
        textArea.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooserAbrir = new javax.swing.JFileChooser();
        painelNorte = new javax.swing.JPanel();
        painelSul = new javax.swing.JPanel();
        btAbrir = new javax.swing.JButton();
        btRefresh = new javax.swing.JButton();
        btCriar = new javax.swing.JButton();
        painelCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        chooserAbrir.setAccessory(btAbrir);
        chooserAbrir.setCurrentDirectory(new java.io.File("C:\\Users\\Allan\\Documents\\NetBeansProjects\\BACKUP TRABALHO\\TRABALHO_POO2"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout painelNorteLayout = new javax.swing.GroupLayout(painelNorte);
        painelNorte.setLayout(painelNorteLayout);
        painelNorteLayout.setHorizontalGroup(
            painelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 885, Short.MAX_VALUE)
        );
        painelNorteLayout.setVerticalGroup(
            painelNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(painelNorte, java.awt.BorderLayout.PAGE_START);

        painelSul.setBackground(new java.awt.Color(204, 204, 204));

        btAbrir.setText("Abrir Banco");
        btAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirActionPerformed(evt);
            }
        });
        painelSul.add(btAbrir);

        btRefresh.setText("Salva Imagem");
        btRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefreshActionPerformed(evt);
            }
        });
        painelSul.add(btRefresh);

        btCriar.setText("Criar Novo Banco");
        btCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCriarActionPerformed(evt);
            }
        });
        painelSul.add(btCriar);

        getContentPane().add(painelSul, java.awt.BorderLayout.PAGE_END);

        painelCentro.setBackground(new java.awt.Color(153, 153, 153));
        painelCentro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 153), 3, true));

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        tabela.setModel(carregarTabela());
        tabela.setToolTipText("Gram-Cruzada-o-Maker");
        tabela.setModel(carregarTabela());
        jScrollPane2.setViewportView(tabela);

        javax.swing.GroupLayout painelCentroLayout = new javax.swing.GroupLayout(painelCentro);
        painelCentro.setLayout(painelCentroLayout);
        painelCentroLayout.setHorizontalGroup(
            painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelCentroLayout.setVerticalGroup(
            painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(painelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarActionPerformed
        // TODO add your handling code here:
        CriadorDeBanco criar = new CriadorDeBanco();
        criar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btCriarActionPerformed

    private void btAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirActionPerformed
        // TODO add your handling code here:
        limparCampos();
        int returnVal = chooserAbrir.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = chooserAbrir.getSelectedFile();
            try {
                BufferedReader reader = new BufferedReader(new FileReader(file));
                String line = "";
                while ((line = reader.readLine()) != null) {
                    makeCard(line);
                }
                System.out.println(listaDePalavras);
                reader.close();           
            } catch (IOException ex) {
                System.out.println("problem accessing file" + file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
        ArrayList<char[]> listaChar = TransformadorDePalavraEmVetor.transformar(listaDePalavras);
        List<char[]> cruzadinha = LogicaCruzadinha.fazerCruzadinha(listaChar);
        ad.setData(cruzadinha);
        
        
    }//GEN-LAST:event_btAbrirActionPerformed

    private void btRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefreshActionPerformed
        
        String nome = JOptionPane.showInputDialog("Nome da imagem");
        GravadorDeImagem.saveComponentAsJPEG(painelCentro ,nome);
    }//GEN-LAST:event_btRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeitorDeCruzadinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeitorDeCruzadinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeitorDeCruzadinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeitorDeCruzadinha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeitorDeCruzadinha().setVisible(true);
            }
        });
    }
    
    private TableModel carregarTabela(){
                
        List<char[]> lista = new Persistencia().list();;
                ad= new PalavraTableModel(lista);
        return ad;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrir;
    private javax.swing.JButton btCriar;
    private javax.swing.JButton btRefresh;
    private javax.swing.JFileChooser chooserAbrir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel painelCentro;
    private javax.swing.JPanel painelNorte;
    private javax.swing.JPanel painelSul;
    private javax.swing.JTable tabela;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Palavra> listaDePalavras = new ArrayList<>();
    private PalavraTableModel ad;
  

}
